import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./app/**/*.{ts,tsx}",
    "./components/**/*.{ts,tsx}",
    "./lib/**/*.{ts,tsx}",
  ],
  theme: {
    container: {
      center: true,
      padding: "2rem",
      screens: {
        "2xl": "1400px",
      },
    },
    extend: {
      colors: {
        background: "#faf8ff",
        surface: "#faf8ff",
        "surface-bright": "#faf8ff",
        "surface-dim": "#d4d9f2",
        "surface-variant": "#dce1fb",
        "surface-container": "#eaedff",
        "surface-container-high": "#e3e7ff",
        "surface-container-highest": "#dce1fb",
        "surface-container-low": "#f2f3ff",
        "surface-container-lowest": "#ffffff",
        primary: "#4212de",
        "primary-container": "#5b3df5",
        "on-primary": "#ffffff",
        "primary-foreground": "#ffffff",
        secondary: "#0051d5",
        "secondary-container": "#316bf3",
        "on-secondary": "#ffffff",
        "on-secondary-container": "#fefcff",
        "secondary-fixed": "#dbe1ff",
        tertiary: "#822f00",
        error: "#ba1a1a",
        "error-container": "#ffdad6",
        outline: "#787588",
        "outline-variant": "#c8c4d9",
        foreground: "#151b2d",
        "on-surface": "#151b2d",
        "on-surface-variant": "#474556",
        "on-background": "#151b2d",
        "surface-tint": "#5738f1",
        "inverse-surface": "#2a3043",
        "inverse-primary": "#c7bfff",
        "inverse-on-surface": "#eef0ff",
        sidebar: "#020617",
        border: "#c8c4d9",
        input: "#c8c4d9",
        ring: "#4212de",
        card: "#ffffff",
        "card-foreground": "#151b2d",
        popover: "#ffffff",
        "popover-foreground": "#151b2d",
        muted: "#f2f3ff",
        "muted-foreground": "#474556",
        accent: "#eaedff",
        "accent-foreground": "#151b2d",
        destructive: "#ba1a1a",
        "destructive-foreground": "#ffffff",
      },
      spacing: {
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "32px",
        unit: "8px",
        "sidebar-width": "280px",
        "container-margin": "40px",
      },
      fontFamily: {
        sans: ["var(--font-inter)", "sans-serif"],
        mono: ["var(--font-geist)", "ui-monospace", "monospace"],
        "body-md": ["var(--font-inter)", "sans-serif"],
        "body-sm": ["var(--font-inter)", "sans-serif"],
        "page-title": ["var(--font-geist)", "sans-serif"],
        "section-title": ["var(--font-geist)", "sans-serif"],
        "label-caps": ["var(--font-geist)", "sans-serif"],
        "mono-data": ["var(--font-geist)", "ui-monospace", "monospace"],
      },
      fontSize: {
        "page-title": [
          "30px",
          { lineHeight: "36px", letterSpacing: "-0.02em", fontWeight: "700" },
        ],
        "section-title": [
          "18px",
          { lineHeight: "24px", fontWeight: "600" },
        ],
        "body-md": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "body-sm": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-caps": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.05em", fontWeight: "600" },
        ],
        "mono-data": ["13px", { lineHeight: "18px", fontWeight: "400" }],
      },
      borderRadius: {
        sm: "0.25rem",
        DEFAULT: "0.25rem",
        md: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      keyframes: {
        "accordion-down": {
          from: { height: "0" },
          to: { height: "var(--radix-accordion-content-height)" },
        },
        "accordion-up": {
          from: { height: "var(--radix-accordion-content-height)" },
          to: { height: "0" },
        },
      },
      animation: {
        "accordion-down": "accordion-down 0.2s ease-out",
        "accordion-up": "accordion-up 0.2s ease-out",
      },
    },
  },
  plugins: [require("tailwindcss-animate")],
};

export default config;
